export const ROUTE_CHANGED = 'router/ROUTE_CHANGED';

export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';

export const UPDATE_BALANCE = 'UPDATE_BALANCE';

export const UPDATE_BET_AMOUNT = 'UPDATE_BET_AMOUNT';

export const UPDATE_BET_SPINNER_STATUS = 'UPDATE_BET_SPINNER_STATUS';

export const SET_OWNER = 'SET_OWNER';